// types/checkout.ts

import { OrderItem } from "./product";

export interface ShippingAddress {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  pincode: string;
  country: string;
}

// Represents the shape of the data strictly collected from the checkout form
export interface CheckoutFormData extends ShippingAddress {
  // If you ever add order notes or alternate payment methods, they go here
  paymentMethod?: "razorpay" | "cod";
}

// Represents the simplified cart item sent to the backend for validation
export interface CartItemCheckout {
  productId: string;
  size: string;
  color: string;
  quantity: number;
}

// Represents the data structure returned by your NestJS POST /api/orders endpoint
// export interface OrderResponse {
//   id: string; // Your database order ID
//   orderNumber: string; // e.g., ATL-2026-043
//   status: string; // e.g., PENDING
//   totalAmount: number; // Subtotal + Shipping + Tax
//   shippingAddress: ShippingAddress;
//   razorpayOrderId?: string;
//   createdAt: string;
//   updatedAt: string;
// }

// Represents the data structure returned by your NestJS POST /api/orders endpoint
export interface OrderResponse {
  id: string;
  orderNumber: string;
  userId: string;
  status: string;
  items: OrderItem[]; // ✅ Properly typed array of items
  shippingAddress: ShippingAddress;
  subtotal: number;
  shippingCost: number;
  tax: number;
  totalAmount: number;
  paymentMethod: string;
  currency: string;
  razorpayOrderId?: string;
  paymentId?: string;
  trackingNumber?: string;

  // 🚚 Logistics & Labelling Extensions (Phase 2 & 3)
  awbCode?: string;
  courierName?: string;
  barcodeValue?: string;
  labelUrl?: string;

  // 🔄 Returns & Replacements (Phase 4)
  returnStatus?: string;
  returnReason?: string;
  returnType?: string;

  createdAt: string;
  updatedAt: string;
}
// Represents the specific payload required to open the Razorpay Checkout Modal
export interface RazorpayOrderResponse {
  razorpayOrderId: string; // The order_id generated by Razorpay
  keyId: string; // Your Razorpay Public Key
  amount: number; // Total amount in rupees (backend handles paise conversion)
  orderId: string; // Your database order ID
  orderNumber: string;
}

// The payload sent to your backend to initiate the order
export interface InitiateCheckoutPayload {
  cartItems: CartItemCheckout[];
  shippingAddress: ShippingAddress;
  paymentMethod: string;
}
