import { api, API_TAGS } from "../api";

// ============================================================================
// 📑 TYPES & DATA INTERFACES
// ============================================================================

export interface CategoryInfo {
  id: string;
  name: string;
  slug: string;
  gender: string;
}

export interface ColorItem {
  name: string;
  value: string;
}

export interface SemanticProductResult {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  images: string[];
  sizes: string[];
  colors: ColorItem[];
  categoryId: string;
  gender: string;
  tags: string[];
  rating: number;
  reviewCount: number;
  isNew: boolean;
  isBestSeller: boolean;
  inStock: boolean;
  inventory: number;
  details: string | null;
  sizing: string | null;
  shipping: string | null;
  createdAt: string;
  updatedAt: string;
  category: CategoryInfo;
  similarityScore: number; // 🧠 Vector similarity rank generated by pgvector
}

export interface SemanticSearchRequest {
  q: string;
  limit?: number;
  threshold?: number;
}

export interface ChatAskRequest {
  message: string;
  sessionId?: string;
}

export interface ChatResponse {
  id: string;
  answer: string;
  properties: string[]; // Product IDs to match inline clickable garment recommendations
}

export interface ChatHistoryItem {
  id: string;
  userId: string;
  sessionId: string;
  question: string;
  answer: string;
  productIds: string[];
  createdAt: string;
}

// ============================================================================
// 🧠 REDUX TOOLKIT QUERY API DEFINITION
// ============================================================================

export const ragApi = api.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * 🔍 Public Semantic Search Query Portal
     * Uses pgvector cosine similarity to resolve natural phrases.
     */
    semanticSearch: builder.query<
      SemanticProductResult[],
      SemanticSearchRequest
    >({
      query: ({ q, limit = 12, threshold = 0.35 }) => ({
        url: "/rag/search",
        method: "GET",
        params: { q, limit, threshold },
      }),
    }),

    /**
     * 💬 Authenticated Personal Stylist Chatbot Mutation
     * Posts inquiries to the Gemini-powered RAG pipeline.
     */
    chatStyleAdvisor: builder.mutation<ChatResponse, ChatAskRequest>({
      query: (body) => ({
        url: "/rag/chat",
        method: "POST",
        data: body, // 🛡️ Changed to 'data' to match your parent API Axios baseQuery
      }),
      // Automatically invalidates the history ledger, forcing a re-fetch of the stream
      invalidatesTags: [API_TAGS.CHATHISTORY],
    }),

    /**
     * 📜 Authenticated Conversation Log Fetcher
     * Pulls historical context for the active panel view.
     */
    getChatHistory: builder.query<
      ChatHistoryItem[],
      { sessionId?: string } | void
    >({
      query: (params) => ({
        url: "/rag/chat/history",
        method: "GET",
        params: params?.sessionId
          ? { sessionId: params.sessionId }
          : { sessionId: "default-chat" },
      }),
      providesTags: [API_TAGS.CHATHISTORY],
    }),

    /**
     * 🗑️ Authenticated Cache Clear Request
     * Wipes conversation lines out of the server state.
     */
    clearChatHistory: builder.mutation<
      { success: boolean },
      { sessionId?: string } | void
    >({
      query: (params) => ({
        url: "/rag/chat/history",
        method: "DELETE",
        params: params?.sessionId
          ? { sessionId: params.sessionId }
          : { sessionId: "default-chat" },
      }),
      invalidatesTags: [API_TAGS.CHATHISTORY],
    }),
  }),
  overrideExisting: false,
});

// ============================================================================
// 📢 EXPORTED HOOKS FOR INTEGRATION
// ============================================================================
export const {
  useSemanticSearchQuery,
  useLazySemanticSearchQuery, // Useful for manually firing on-demand text searches
  useChatStyleAdvisorMutation,
  useGetChatHistoryQuery,
  useClearChatHistoryMutation,
} = ragApi;
